### ISSUE TITLE
Baseline comparison

### ISSUE THREAD

**Issue by HashmatShadab** [speedlab-git/SimCLIP#2]
![image](https://github.com/user-attachments/assets/dc86d204-17be-42da-9012-75efad5aa34b)
![image](https://github.com/user-attachments/assets/33577487-8efa-421d-ad27-b1be7b0420ec)

On the task of COCO and Flickr30k, why are the clean and adversarial evaluation results different from what is reported in the RobustCLIP paper?

**Comment by hossainzarif** [comment]
We used FARE as the baseline for our comparison, and the results in our table were obtained from our own inference. Rather than simply taking their reported scores at face value, we ran the inference ourselves using their encoder. The results presented in our table are based on this independent evaluation.

**Comment by HashmatShadab** [comment]
Thank you for the clarification. Could you further explain why there's a notable difference between the two results? Were there any major changes in your attack setup compared to FARE?

**Comment by hossainzarif** [comment]
One notable difference in our implementation is that, unlike FARE, which used two different precisions during the attack (likely to reduce computational costs), we used a single precision attack throughout our process.

**Comment by HashmatShadab** [comment]
Got it. Thanks!
